// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MrKatsuWebAPI.DataAccess;

#nullable disable

namespace MrKatsuWebAPI.DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250429080828_AddPropMod")]
    partial class AddPropMod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("ConcurrencyStamp")
                        .HasDatabaseName("IX_Roles_ConcurrencyStamp");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("IX_Roles_NormalizedName");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Admintrator",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Admintrator",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("access_failed_count");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("")
                        .HasColumnName("avatar");

                    b.Property<string>("ConcurrencyStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("LockoutEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("longtext")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("longtext")
                        .HasColumnName("normalized_username");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("")
                        .HasColumnName("security_stamp");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("time_created");

                    b.Property<DateTime>("TimeUpdated")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("time_updated");

                    b.Property<bool>("TwoFactorEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_UserName");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Avatar = "assets/images/avatars/564.png",
                            ConcurrencyStamp = "21b1255e-a151-491e-86f7-dfda42d8a148",
                            Email = "admin@mail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEEgVBtLYIhc1Wmz+YAk/jqAYNdkvLoFUaBbX4LdI8kv7tFfPPYuBhUL7y12ZwsMeqw==",
                            PhoneNumberConfirmed = false,
                            TimeCreated = new DateTime(2025, 4, 29, 15, 8, 26, 946, DateTimeKind.Local).AddTicks(7797),
                            TimeUpdated = new DateTime(2025, 4, 29, 15, 8, 26, 946, DateTimeKind.Local).AddTicks(7797),
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Avatar = "assets/images/avatars/vip/1475.png",
                            ConcurrencyStamp = "37249530-2b62-4793-89fe-306a21e64dc8",
                            Email = "hunghero@mail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "HUNGHERO@MAIL.COM",
                            NormalizedUserName = "HUNGHERO",
                            PasswordHash = "AQAAAAIAAYagAAAAEAl4oTP5WcY1aynxlCO0DFlBA8whX5yw/CcecwwJzC+h2fQ3ySDG2DZAJOSH37I5HA==",
                            PhoneNumberConfirmed = false,
                            TimeCreated = new DateTime(2025, 4, 29, 15, 8, 27, 12, DateTimeKind.Local).AddTicks(3473),
                            TimeUpdated = new DateTime(2025, 4, 29, 15, 8, 27, 12, DateTimeKind.Local).AddTicks(3473),
                            TwoFactorEnabled = false,
                            UserName = "hunghero"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Avatar = "assets/images/avatars/vip/1360.png",
                            ConcurrencyStamp = "28c961ea-1a45-49c6-ba9f-c888b73d0bfa",
                            Email = "katsu@mail.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "KATSU@MAIL.COM",
                            NormalizedUserName = "KATSU",
                            PasswordHash = "AQAAAAIAAYagAAAAEOL+tVhN0EL1TRA55NjxlSmTRL8fhUl/IbjGD+cZIA9qvq2YZtpWFvvGpa26QvbVvA==",
                            PhoneNumberConfirmed = false,
                            TimeCreated = new DateTime(2025, 4, 29, 15, 8, 27, 169, DateTimeKind.Local).AddTicks(9659),
                            TimeUpdated = new DateTime(2025, 4, 29, 15, 8, 27, 169, DateTimeKind.Local).AddTicks(9681),
                            TwoFactorEnabled = false,
                            UserName = "katsu"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Avatar = "assets/images/avatars/vip/1361.png",
                            ConcurrencyStamp = "d54c5582-0129-4afe-817c-449fffa29069",
                            Email = "gatapchoi@email.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GATAPCHOI@EMAIL.COM",
                            NormalizedUserName = "GATAPCHOI",
                            PasswordHash = "AQAAAAIAAYagAAAAEG2mVMq7NUOMgw2kLkTv/GVrZuDLVlTmq+espm+M+w/U6CPgP5gHMPX+dVOOi2i6ag==",
                            PhoneNumberConfirmed = false,
                            TimeCreated = new DateTime(2025, 4, 29, 15, 8, 27, 251, DateTimeKind.Local).AddTicks(1253),
                            TimeUpdated = new DateTime(2025, 4, 29, 15, 8, 27, 251, DateTimeKind.Local).AddTicks(1270),
                            TwoFactorEnabled = false,
                            UserName = "gatapchoi"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Avatar = "assets/images/avatars/vip/1474.png",
                            ConcurrencyStamp = "4e5f9d7e-266c-4339-80b0-71a240c0311d",
                            Email = "manhhdc@email.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MANHHDC@EMAIL.COM",
                            NormalizedUserName = "MANHHDC",
                            PasswordHash = "AQAAAAIAAYagAAAAENPMWeyU/Uxe9MRV7/zskRnRr2l8G9a4ObUeexTmFwCd+fH68Q5IK8AEx0HpSealTQ==",
                            PhoneNumberConfirmed = false,
                            TimeCreated = new DateTime(2025, 4, 29, 15, 8, 27, 324, DateTimeKind.Local).AddTicks(9482),
                            TimeUpdated = new DateTime(2025, 4, 29, 15, 8, 27, 324, DateTimeKind.Local).AddTicks(9503),
                            TwoFactorEnabled = false,
                            UserName = "manhhdc"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            Avatar = "assets/images/avatars/1209.png",
                            ConcurrencyStamp = "cfa01993-83e2-416b-9f1a-add8dd6ddd22",
                            Email = "ehvn@email.com",
                            EmailConfirmed = false,
                            IsDeleted = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ehvn@email.com",
                            NormalizedUserName = "EHVN",
                            PasswordHash = "AQAAAAIAAYagAAAAENaR/Vv8kE8usxCZtDMMFQCBLARG1c1vkxBEV0D76/Wfk3F1WwozoQYc7936LuQqRA==",
                            PhoneNumberConfirmed = false,
                            TimeCreated = new DateTime(2025, 4, 29, 15, 8, 27, 403, DateTimeKind.Local).AddTicks(9258),
                            TimeUpdated = new DateTime(2025, 4, 29, 15, 8, 27, 403, DateTimeKind.Local).AddTicks(9292),
                            TwoFactorEnabled = false,
                            UserName = "ehvn"
                        });
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Category", b =>
                {
                    b.Property<byte>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<byte>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Description = "Chi tiết danh mục",
                            Name = "android"
                        },
                        new
                        {
                            Id = (byte)2,
                            Description = "Chi tiết danh mục",
                            Name = "pc"
                        },
                        new
                        {
                            Id = (byte)3,
                            Description = "Chi tiết danh mục",
                            Name = "java"
                        },
                        new
                        {
                            Id = (byte)4,
                            Description = "Chi tiết danh mục",
                            Name = "ios"
                        });
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Mod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("CategoryId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 8, 8, 26, 942, DateTimeKind.Utc).AddTicks(1980))
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPrivate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_private");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 8, 8, 26, 942, DateTimeKind.Utc).AddTicks(2895))
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("mods", (string)null);
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 8, 8, 26, 943, DateTimeKind.Utc).AddTicks(1553))
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 8, 8, 26, 943, DateTimeKind.Utc).AddTicks(2564))
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Posts_IsDeleted");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Posts_UpdatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Posts_UserId");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Reaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 8, 8, 26, 944, DateTimeKind.Utc).AddTicks(156))
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("ModId")
                        .HasColumnType("int")
                        .HasColumnName("mod_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 8, 8, 26, 944, DateTimeKind.Utc).AddTicks(1046))
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Reactions_UpdatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Reactions_UserId");

                    b.ToTable("reactions", (string)null);
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 8, 8, 26, 944, DateTimeKind.Utc).AddTicks(9629))
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int>("PostId")
                        .HasColumnType("int")
                        .HasColumnName("post_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 8, 8, 26, 945, DateTimeKind.Utc).AddTicks(622))
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted")
                        .HasDatabaseName("IX_Replies_IsDeleted");

                    b.HasIndex("ParentId");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_Replies_PostId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Replies_UpdatedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Replies_UserId");

                    b.ToTable("replies", (string)null);
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Url", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 8, 8, 26, 945, DateTimeKind.Utc).AddTicks(8908))
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("ModId")
                        .HasColumnType("int")
                        .HasColumnName("mod_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValue(new DateTime(2025, 4, 29, 8, 8, 26, 945, DateTimeKind.Utc).AddTicks(9743))
                        .HasColumnName("updated_at");

                    b.Property<string>("UrlString")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("url_string");

                    b.HasKey("Id");

                    b.HasIndex("ModId");

                    b.ToTable("urls", (string)null);
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Mod", b =>
                {
                    b.HasOne("MrKatsuWebAPI.DataAccess.Entities.Category", "Category")
                        .WithMany("Mods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MrKatsuWebAPI.DataAccess.Entities.AppUser", "User")
                        .WithMany("Mods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Post", b =>
                {
                    b.HasOne("MrKatsuWebAPI.DataAccess.Entities.AppUser", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Reaction", b =>
                {
                    b.HasOne("MrKatsuWebAPI.DataAccess.Entities.Mod", "Mod")
                        .WithMany("Reactions")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MrKatsuWebAPI.DataAccess.Entities.AppUser", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Reply", b =>
                {
                    b.HasOne("MrKatsuWebAPI.DataAccess.Entities.Reply", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.HasOne("MrKatsuWebAPI.DataAccess.Entities.Post", "Post")
                        .WithMany("Replies")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MrKatsuWebAPI.DataAccess.Entities.AppUser", "User")
                        .WithMany("Replies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Url", b =>
                {
                    b.HasOne("MrKatsuWebAPI.DataAccess.Entities.Mod", "Mod")
                        .WithMany("Urls")
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mod");
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.AppUser", b =>
                {
                    b.Navigation("Mods");

                    b.Navigation("Posts");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Category", b =>
                {
                    b.Navigation("Mods");
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Mod", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Urls");
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Post", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("MrKatsuWebAPI.DataAccess.Entities.Reply", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
